name: Qt C++ CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
      - ui-team
      - query-team
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.0'
          cache: true

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build
