name: Qt C++ CI

on:
  push:
    branches:
      - main
      - ui-team
      - query-team

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'

      - name: Check qmake
        run: qmake --version

      - name: Run qmake
        run: qmake Campus.pro

      - name: Build Project
        run: make